In [0]:
# main libraries
import pandas as pd
import numpy as np
# sklearn libraries
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [0]:
import requests
import io

response = requests.get('http://www.utdallas.edu/~jxz172130/data/train.csv')

file_object = io.StringIO(response.content.decode('utf-8'))
df = pd.read_csv(file_object)

In [25]:
df.head()

id  feat_1  feat_2  feat_3  feat_4  feat_5  feat_6  feat_7  feat_8  feat_9  \
0   1       1       0       0       0       0       0       0       0       0   
1   2       0       0       0       0       0       0       0       1       0   
2   3       0       0       0       0       0       0       0       1       0   
3   4       1       0       0       1       6       1       5       0       0   
4   5       0       0       0       0       0       0       0       0       0   

   ...  feat_85  feat_86  feat_87  feat_88  feat_89  feat_90  feat_91  \
0  ...        1        0        0        0        0        0        0   
1  ...        0        0        0        0        0        0        0   
2  ...        0        0        0        0        0        0        0   
3  ...        0        1        2        0        0        0        0   
4  ...        1        0        0        0        0        1        0   

   feat_92  feat_93   target  
0        0        0  Class_1  
1        0        0  Class_1  
2        0        0  Class_1  
3        0        0  Class_1  
4        0        0  Class_1  

[5 rows x 95 columns]

### converting categorical to numerical values


In [26]:
cleanup_nums = {"target": {"Class_1": 0, "Class_2": 1, "Class_3": 2, "Class_4": 3, "Class_5": 4, "Class_6": 5, "Class_7": 6, "Class_8": 7, "Class_9": 8}}
df.replace(cleanup_nums, inplace=True)
df.head()

id  feat_1  feat_2  feat_3  feat_4  feat_5  feat_6  feat_7  feat_8  feat_9  \
0   1       1       0       0       0       0       0       0       0       0   
1   2       0       0       0       0       0       0       0       1       0   
2   3       0       0       0       0       0       0       0       1       0   
3   4       1       0       0       1       6       1       5       0       0   
4   5       0       0       0       0       0       0       0       0       0   

   ...  feat_85  feat_86  feat_87  feat_88  feat_89  feat_90  feat_91  \
0  ...        1        0        0        0        0        0        0   
1  ...        0        0        0        0        0        0        0   
2  ...        0        0        0        0        0        0        0   
3  ...        0        1        2        0        0        0        0   
4  ...        1        0        0        0        0        1        0   

   feat_92  feat_93  target  
0        0        0       0  
1        0        0       0  
2        0        0       0  
3        0        0       0  
4        0        0       0  

[5 rows x 95 columns]

# Data Preparation

In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
scaler = StandardScaler()

In [29]:
scaler.fit(df.drop(['id','target'],axis=1))

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [30]:

scaled_features = scaler.fit_transform(df.drop(['id','target'],axis=1))

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/usr/local/lib/python3.6/dist-packages/sklearn/base.py:464: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [31]:
df_feat = pd.DataFrame(scaled_features,columns=df.columns[1:-1])
df_feat.head()

feat_1    feat_2    feat_3    feat_4     feat_5    feat_6    feat_7  \
0  0.402093 -0.210106 -0.307165 -0.279443  -0.161867 -0.119331 -0.188045   
1 -0.253508 -0.210106 -0.307165 -0.279443  -0.161867 -0.119331 -0.188045   
2 -0.253508 -0.210106 -0.307165 -0.279443  -0.161867 -0.119331 -0.188045   
3  0.402093 -0.210106 -0.307165  0.079240  13.508710  4.524667  4.665884   
4 -0.253508 -0.210106 -0.307165 -0.279443  -0.161867 -0.119331 -0.188045   

     feat_8    feat_9   feat_10  ...    feat_84   feat_85   feat_86   feat_87  \
0 -0.293664 -0.291038 -0.243606  ...  -0.061446  0.246100 -0.420870 -0.249802   
1  0.149647 -0.291038 -0.243606  ...  -0.061446 -0.280099 -0.420870 -0.249802   
2  0.149647 -0.291038 -0.243606  ...  -0.061446 -0.280099 -0.420870 -0.249802   
3 -0.293664 -0.291038  0.679472  ...  19.044887 -0.280099 -0.047949  1.019683   
4 -0.293664 -0.291038 -0.243606  ...  -0.061446  0.246100 -0.420870 -0.249802   

    feat_88   feat_89   feat_90   feat_91   feat_92   feat_93  
0 -0.413584 -0.299712 -0.176699 -0.129516 -0.386938 -0.104963  
1 -0.413584 -0.299712 -0.176699 -0.129516 -0.386938 -0.104963  
2 -0.413584 -0.299712 -0.176699 -0.129516 -0.386938 -0.104963  
3 -0.413584 -0.299712 -0.176699 -0.129516 -0.386938 -0.104963  
4 -0.413584 -0.299712  0.040798 -0.129516 -0.386938 -0.104963  

[5 rows x 93 columns]

In [0]:
# nrows, ncols = df.shape[0], df.shape[1]
# X = df.iloc[:, 1:(ncols - 1)].values.reshape(nrows, ncols - 2)
# y = df.iloc[:, (ncols - 1)].values.reshape(nrows, 1)

In [0]:
# X

# Training Test Split

In [0]:
X = df_feat
y = df['target']

In [35]:
X = X.as_matrix()
y = y.as_matrix()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# Train Dataset

In [0]:
from xgboost import XGBClassifier

In [0]:
classifier = XGBClassifier(base_score=0.5, 
                           booster='gbtree', 
                           colsample_bylevel=1,
                           colsample_bytree=1, 
                           gamma=0, 
                           learning_rate=0.3, 
                           max_delta_step=0,      
                           max_depth=4, 
                           min_child_weight=1, 
                           missing=None, 
                           n_estimators=100,     
                           n_jobs=1, 
                           nthread=None, 
                           objective='multi:softprob', 
                           random_state=0,      
                           reg_alpha=0, 
                           reg_lambda=1, 
                           scale_pos_weight=1, 
                           seed=None,
                           silent=False, 
                           subsample=1)

In [40]:
classifier.fit(X_train, y_train, eval_metric='mlogloss', verbose=True,
            eval_set=[(X_test, y_test)], early_stopping_rounds=100)

[0]	validation_0-mlogloss:1.61189
Will train until validation_0-mlogloss hasn't improved in 100 rounds.
[1]	validation_0-mlogloss:1.37808
[2]	validation_0-mlogloss:1.22224
[3]	validation_0-mlogloss:1.11013
[4]	validation_0-mlogloss:1.02718
[5]	validation_0-mlogloss:0.961029
[6]	validation_0-mlogloss:0.907282
[7]	validation_0-mlogloss:0.862817
[8]	validation_0-mlogloss:0.82837
[9]	validation_0-mlogloss:0.799103
[10]	validation_0-mlogloss:0.776023
[11]	validation_0-mlogloss:0.755365
[12]	validation_0-mlogloss:0.737499
[13]	validation_0-mlogloss:0.722856
[14]	validation_0-mlogloss:0.709207
[15]	validation_0-mlogloss:0.697457
[16]	validation_0-mlogloss:0.686385
[17]	validation_0-mlogloss:0.678126
[18]	validation_0-mlogloss:0.669618
[19]	validation_0-mlogloss:0.66124
[20]	validation_0-mlogloss:0.654144
[21]	validation_0-mlogloss:0.647452
[22]	validation_0-mlogloss:0.64132
[23]	validation_0-mlogloss:0.635964
[24]	validation_0-mlogloss:0.630192
[25]	validation_0-mlogloss:0.625586
[26]	validat

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.3, max_delta_step=0,
       max_depth=4, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=False, subsample=1)

# Prediction of Test Set

In [0]:
import requests
import io

response = requests.get('http://www.utdallas.edu/~jxz172130/data/test.csv')

file_object = io.StringIO(response.content.decode('utf-8'))
dfTest = pd.read_csv(file_object)

dfTest = dfTest.drop('id',axis=1)

In [0]:
y_pred = classifier.predict(X_test)

In [0]:
from sklearn import metrics

In [45]:
score = metrics.accuracy_score(y_test, y_pred)
print('Accuracy: {0:f}'.format(score))

Accuracy: 0.801498


In [0]:
from sklearn.metrics import classification_report, confusion_matrix

In [47]:
print(confusion_matrix(y_test, y_pred))

[[ 280   15    4    1    2   52   15   86  104]
 [   2 4146  541   57    7   10   31   10    4]
 [   1 1187 1104   33    0    4   65    3    4]
 [   0  285  134  381    6   26   17    2    2]
 [   1   21    0    1  799    2    3    3    1]
 [  26   54    1    7    1 4014   61   57   53]
 [  17   89   56   14    3   58  516   40    7]
 [  40   37    6    0    3   56   18 2332   41]
 [  53   29    0    1    3   54    5   53 1307]]


In [48]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.67      0.50      0.57       559
           1       0.71      0.86      0.78      4808
           2       0.60      0.46      0.52      2401
           3       0.77      0.45      0.57       853
           4       0.97      0.96      0.97       831
           5       0.94      0.94      0.94      4274
           6       0.71      0.65      0.67       800
           7       0.90      0.92      0.91      2533
           8       0.86      0.87      0.86      1505

   micro avg       0.80      0.80      0.80     18564
   macro avg       0.79      0.73      0.75     18564
weighted avg       0.80      0.80      0.79     18564



#  Overwrite to the Submission file

In [49]:
import requests
import io

response = requests.get('http://www.utdallas.edu/~jxz172130/data/submission1.csv')

file_object = io.StringIO(response.content.decode('utf-8'))
df_submission = pd.read_csv(file_object)

df_submission

id  Class_1  Class_2  Class_3  Class_4  Class_5  Class_6  Class_7  \
0            1        0        0        0        0        0        0        0   
1            2        0        0        0        0        0        0        0   
2            3        0        0        0        0        0        0        0   
3            4        0        0        0        0        0        0        0   
4            5        0        0        0        0        0        0        0   
5            6        0        0        0        0        0        0        0   
6            7        0        0        0        0        0        0        0   
7            8        0        0        0        0        0        0        0   
8            9        0        0        0        0        0        0        0   
9           10        0        0        0        0        0        0        0   
10          11        0        0        0        0        0        0        0   
11          12        0        0        0        0        0        0        0   
12          13        0        0        0        0        0        0        0   
13          14        0        0        0        0        0        0        0   
14          15        0        0        0        0        0        0        0   
15          16        0        0        0        0        0        0        0   
16          17        0        0        0        0        0        0        0   
17          18        0        0        0        0        0        0        0   
18          19        0        0        0        0        0        0        0   
19          20        0        0        0        0        0        0        0   
20          21        0        0        0        0        0        0        0   
21          22        0        0        0        0        0        0        0   
22          23        0        0        0        0        0        0        0   
23          24        0        0        0        0        0        0        0   
24          25        0        0        0        0        0        0        0   
25          26        0        0        0        0        0        0        0   
26          27        0        0        0        0        0        0        0   
27          28        0        0        0        0        0        0        0   
28          29        0        0        0        0        0        0        0   
29          30        0        0        0        0        0        0        0   
...        ...      ...      ...      ...      ...      ...      ...      ...   
144338  144339        0        0        0        0        0        0        0   
144339  144340        0        0        0        0        0        0        0   
144340  144341        0        0        0        0        0        0        0   
144341  144342        0        0        0        0        0        0        0   
144342  144343        0        0        0        0        0        0        0   
144343  144344        0        0        0        0        0        0        0   
144344  144345        0        0        0        0        0        0        0   
144345  144346        0        0        0        0        0        0        0   
144346  144347        0        0        0        0        0        0        0   
144347  144348        0        0        0        0        0        0        0   
144348  144349        0        0        0        0        0        0        0   
144349  144350        0        0        0        0        0        0        0   
144350  144351        0        0        0        0        0        0        0   
144351  144352        0        0        0        0        0        0        0   
144352  144353        0        0        0        0        0        0        0   
144353  144354        0        0        0        0        0        0        0   
144354  144355        0        0        0        0        0        0        0   
144355  144356        0        0        0  

In [50]:
df_submission = df_submission.as_matrix()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [51]:
type(df_submission)

numpy.ndarray

In [0]:
j = 0
for i in y_pred:
  df_submission[j][i + 1] = 1
  j += 1

In [53]:
#np.delete(df_submission, 0, 1)
df_submission

array([[     1,      0,      0, ...,      0,      0,      0],
       [     2,      0,      0, ...,      0,      0,      0],
       [     3,      0,      1, ...,      0,      0,      0],
       ...,
       [144366,      0,      0, ...,      0,      0,      0],
       [144367,      0,      0, ...,      0,      0,      0],
       [144368,      0,      0, ...,      0,      0,      0]])

In [54]:
df_file = pd.DataFrame(df_submission, columns=["id", "Class_1", "Class_2", "Class_3", "Class_4", "Class_5", "Class_6", "Class_7", "Class_8", "Class_9"])
df_file

id  Class_1  Class_2  Class_3  Class_4  Class_5  Class_6  Class_7  \
0            1        0        0        1        0        0        0        0   
1            2        0        0        0        0        1        0        0   
2            3        0        1        0        0        0        0        0   
3            4        0        1        0        0        0        0        0   
4            5        0        0        1        0        0        0        0   
5            6        0        1        0        0        0        0        0   
6            7        0        0        0        0        0        0        0   
7            8        0        1        0        0        0        0        0   
8            9        0        0        1        0        0        0        0   
9           10        0        0        0        1        0        0        0   
10          11        0        0        1        0        0        0        0   
11          12        0        0        0        0        0        1        0   
12          13        0        0        0        0        0        0        0   
13          14        0        0        0        0        0        0        0   
14          15        0        0        1        0        0        0        0   
15          16        0        0        0        0        0        1        0   
16          17        0        0        0        0        0        1        0   
17          18        0        1        0        0        0        0        0   
18          19        0        1        0        0        0        0        0   
19          20        0        0        0        0        0        0        0   
20          21        0        1        0        0        0        0        0   
21          22        0        1        0        0        0        0        0   
22          23        0        0        1        0        0        0        0   
23          24        0        0        0        0        0        1        0   
24          25        0        0        0        0        0        1        0   
25          26        0        0        1        0        0        0        0   
26          27        0        0        1        0        0        0        0   
27          28        0        1        0        0        0        0        0   
28          29        0        1        0        0        0        0        0   
29          30        0        0        1        0        0        0        0   
...        ...      ...      ...      ...      ...      ...      ...      ...   
144338  144339        0        0        0        0        0        0        0   
144339  144340        0        0        0        0        0        0        0   
144340  144341        0        0        0        0        0        0        0   
144341  144342        0        0        0        0        0        0        0   
144342  144343        0        0        0        0        0        0        0   
144343  144344        0        0        0        0        0        0        0   
144344  144345        0        0        0        0        0        0        0   
144345  144346        0        0        0        0        0        0        0   
144346  144347        0        0        0        0        0        0        0   
144347  144348        0        0        0        0        0        0        0   
144348  144349        0        0        0        0        0        0        0   
144349  144350        0        0        0        0        0        0        0   
144350  144351        0        0        0        0        0        0        0   
144351  144352        0        0        0        0        0        0        0   
144352  144353        0        0        0        0        0        0        0   
144353  144354        0        0        0        0        0        0        0   
144354  144355        0        0        0        0        0        0        0   
144355  144356        0        0        0  

In [0]:
predictionFile = df_file.to_csv('prediction.csv', index=False)

In [0]:
from google.colab import files
files.download('prediction.csv')